// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/booleanism/oapi-codegen/v2 version v2.5.1-p5 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for FeedType.
const (
	FeedTypeA FeedType = "a"
	FeedTypeJ FeedType = "j"
	FeedTypeM FeedType = "m"
	FeedTypeS FeedType = "s"
)

// Defines values for NewFeedReqType.
const (
	NewFeedReqTypeA NewFeedReqType = "a"
	NewFeedReqTypeJ NewFeedReqType = "j"
	NewFeedReqTypeM NewFeedReqType = "m"
	NewFeedReqTypeS NewFeedReqType = "s"
)

// Defines values for GetFeedsParamsType.
const (
	A GetFeedsParamsType = "a"
	J GetFeedsParamsType = "j"
	M GetFeedsParamsType = "m"
	S GetFeedsParamsType = "s"
)

// DeleteRes defines model for DeleteRes.
type DeleteRes struct {
	// Code Represent return result code of request. If it was negative, error happen at server side and mostly with 5xx status code.
	// If it was positive, you are the error. Either, success.
	Code int                 `json:"code"`
	Id   *openapi_types.UUID `json:"id,omitempty"`

	// Message This explain what's going on within result code.
	Message string `json:"message"`
}

// Feed defines model for Feed.
type Feed struct {
	CreatedAt *openapi_types.Date `json:"created_at,omitempty"`
	DeletedAt *openapi_types.Date `json:"deleted_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	NComments *int                `json:"n_comments,omitempty"`
	Points    *int                `json:"points,omitempty"`
	Text      *string             `json:"text,omitempty"`
	Title     *string             `json:"title,omitempty"`
	Type      *FeedType           `json:"type,omitempty"`
	Url       *string             `json:"url,omitempty"`
}

// FeedType defines model for Feed.Type.
type FeedType string

// GenericRes defines model for GenericRes.
type GenericRes struct {
	// Code Represent return result code of request. If it was negative, error happen at server side and mostly with 5xx status code.
	// If it was positive, you are the error. Either, success.
	Code int `json:"code"`

	// Message This explain what's going on within result code.
	Message string `json:"message"`
}

// GetFeedsRes defines model for GetFeedsRes.
type GetFeedsRes struct {
	// Code Represent return result code of request. If it was negative, error happen at server side and mostly with 5xx status code.
	// If it was positive, you are the error. Either, success.
	Code int `json:"code"`

	// Details Feed(s) representation.
	Details *[]Feed `json:"details,omitempty"`

	// Message This explain what's going on within result code.
	Message string `json:"message"`
}

// NewFeedReq defines model for NewFeedReq.
type NewFeedReq struct {
	Text  *string        `json:"text,omitempty"`
	Title string         `json:"title"`
	Type  NewFeedReqType `json:"type"`
	Url   *string        `json:"url,omitempty"`
}

// NewFeedReqType defines model for NewFeedReq.Type.
type NewFeedReqType string

// NewFeedRes defines model for NewFeedRes.
type NewFeedRes struct {
	// Code Represent return result code of request. If it was negative, error happen at server side and mostly with 5xx status code.
	// If it was positive, you are the error. Either, success.
	Code int `json:"code"`

	// Message This explain what's going on within result code.
	Message string `json:"message"`
}

// GetFeedsParams defines parameters for GetFeeds.
type GetFeedsParams struct {
	// Type The type of feed, either m (main), a (ask), j (job), s (show).
	Type GetFeedsParamsType `form:"type" json:"type"`

	// Id ID of the feed.
	Id *openapi_types.UUID `form:"id,omitempty" json:"id,omitempty"`

	// Offset The offset of the feeds, multiplied by 30. If you pass 1, it would return feeds range of 31-60. Default: 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetFeedsParamsType defines parameters for GetFeeds.
type GetFeedsParamsType string

// NewFeedJSONRequestBody defines body for NewFeed for application/json ContentType.
type NewFeedJSONRequestBody = NewFeedReq

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetFeeds request
	GetFeeds(ctx context.Context, params *GetFeedsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// NewFeedWithBody request with any body
	NewFeedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NewFeed(ctx context.Context, body NewFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteFeed request
	DeleteFeed(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetFeeds(ctx context.Context, params *GetFeedsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFeedsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NewFeedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewFeedRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NewFeed(ctx context.Context, body NewFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewFeedRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteFeed(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteFeedRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetFeedsRequest generates requests for GetFeeds
func NewGetFeedsRequest(server string, params *GetFeedsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, params.Type); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "id", runtime.ParamLocationQuery, *params.Id); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewNewFeedRequest calls the generic NewFeed builder with application/json body
func NewNewFeedRequest(server string, body NewFeedJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNewFeedRequestWithBody(server, "application/json", bodyReader)
}

// NewNewFeedRequestWithBody generates requests for NewFeed with any type of body
func NewNewFeedRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteFeedRequest generates requests for DeleteFeed
func NewDeleteFeedRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetFeedsWithResponse request
	GetFeedsWithResponse(ctx context.Context, params *GetFeedsParams, reqEditors ...RequestEditorFn) (*GetFeedsResponse, error)

	// NewFeedWithBodyWithResponse request with any body
	NewFeedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewFeedResponse, error)

	NewFeedWithResponse(ctx context.Context, body NewFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*NewFeedResponse, error)

	// DeleteFeedWithResponse request
	DeleteFeedWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteFeedResponse, error)
}

type GetFeedsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetFeedsRes
	JSON400      *GenericRes
	JSON404      *GenericRes
	JSON500      *GenericRes
}

// Status returns HTTPResponse.Status
func (r GetFeedsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFeedsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type NewFeedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *NewFeedRes
	JSON401      *GenericRes
	JSON500      *GenericRes
}

// Status returns HTTPResponse.Status
func (r NewFeedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NewFeedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteFeedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *DeleteRes
	JSON204      *DeleteRes
	JSON401      *GenericRes
	JSON500      *GenericRes
}

// Status returns HTTPResponse.Status
func (r DeleteFeedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteFeedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetFeedsWithResponse request returning *GetFeedsResponse
func (c *ClientWithResponses) GetFeedsWithResponse(ctx context.Context, params *GetFeedsParams, reqEditors ...RequestEditorFn) (*GetFeedsResponse, error) {
	rsp, err := c.GetFeeds(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFeedsResponse(rsp)
}

// NewFeedWithBodyWithResponse request with arbitrary body returning *NewFeedResponse
func (c *ClientWithResponses) NewFeedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewFeedResponse, error) {
	rsp, err := c.NewFeedWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewFeedResponse(rsp)
}

func (c *ClientWithResponses) NewFeedWithResponse(ctx context.Context, body NewFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*NewFeedResponse, error) {
	rsp, err := c.NewFeed(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewFeedResponse(rsp)
}

// DeleteFeedWithResponse request returning *DeleteFeedResponse
func (c *ClientWithResponses) DeleteFeedWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteFeedResponse, error) {
	rsp, err := c.DeleteFeed(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteFeedResponse(rsp)
}

// ParseGetFeedsResponse parses an HTTP response from a GetFeedsWithResponse call
func ParseGetFeedsResponse(rsp *http.Response) (*GetFeedsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFeedsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetFeedsRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GenericRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest GenericRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GenericRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseNewFeedResponse parses an HTTP response from a NewFeedWithResponse call
func ParseNewFeedResponse(rsp *http.Response) (*NewFeedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NewFeedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest NewFeedRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest GenericRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GenericRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteFeedResponse parses an HTTP response from a DeleteFeedWithResponse call
func ParseDeleteFeedResponse(rsp *http.Response) (*DeleteFeedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteFeedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest DeleteRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 204:
		var dest DeleteRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON204 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest GenericRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GenericRes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get feed(s)
	// (GET /)
	GetFeeds(c fiber.Ctx, params GetFeedsParams) error
	// Creates new feed
	// (POST /)
	NewFeed(c fiber.Ctx) error
	// Delete a feed
	// (DELETE /{id})
	DeleteFeed(c fiber.Ctx, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
	ErrFn   func(c fiber.Ctx, err error) error
}

type MiddlewareFunc fiber.Handler

// GetFeeds operation middleware
func (siw *ServerInterfaceWrapper) GetFeeds(c fiber.Ctx) error {

	var err error

	header := c.GetReqHeaders()

	authHeader, _ := header["Authorization"]

	token, _ := strings.CutPrefix(authHeader[len(authHeader)-1], "Bearer ")

	c.Locals("bearerAuth", token)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFeedsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return siw.ErrFn(c, err)
		// return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "type" -------------

	if paramValue := c.Query("type"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument type is required, but not found")
		return siw.ErrFn(c, err)
	}

	err = runtime.BindQueryParameter("form", true, true, "type", query, &params.Type)
	if err != nil {
		return siw.ErrFn(c, err)
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", query, &params.Id)
	if err != nil {
		return siw.ErrFn(c, err)
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return siw.ErrFn(c, err)
	}

	return siw.Handler.GetFeeds(c, params)
}

// NewFeed operation middleware
func (siw *ServerInterfaceWrapper) NewFeed(c fiber.Ctx) error {

	header := c.GetReqHeaders()

	authHeader, ok := header["Authorization"]
	if !ok {
		return siw.ErrFn(c, fmt.Errorf("Missing Authorization header"))
	}

	if len(authHeader) > 1 {
		return siw.ErrFn(c, fmt.Errorf("Ambigous Authorization header"))
	}

	token, ok := strings.CutPrefix(authHeader[len(authHeader)-1], "Bearer ")
	if !ok {
		return siw.ErrFn(c, fmt.Errorf("Invalid Authorization scheme"))
	}

	c.Locals("bearerAuth", token)

	return siw.Handler.NewFeed(c)
}

// DeleteFeed operation middleware
func (siw *ServerInterfaceWrapper) DeleteFeed(c fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return siw.ErrFn(c, err)
		// return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	header := c.GetReqHeaders()

	authHeader, ok := header["Authorization"]
	if !ok {
		return siw.ErrFn(c, fmt.Errorf("Missing Authorization header"))
	}

	if len(authHeader) > 1 {
		return siw.ErrFn(c, fmt.Errorf("Ambigous Authorization header"))
	}

	token, ok := strings.CutPrefix(authHeader[len(authHeader)-1], "Bearer ")
	if !ok {
		return siw.ErrFn(c, fmt.Errorf("Invalid Authorization scheme"))
	}

	c.Locals("bearerAuth", token)

	return siw.Handler.DeleteFeed(c, id)
}

type OpName = string

const (
	OpNameValueGetFeeds OpName = "GetFeeds"

	OpNameValueNewFeed OpName = "NewFeed"

	OpNameValueDeleteFeed OpName = "DeleteFeed"
)

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface, hs map[OpName][]fiber.Handler, errFn func(c fiber.Ctx, err error) error) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{}, hs, errFn)
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions, hs map[OpName][]fiber.Handler, errFn func(c fiber.Ctx, err error) error) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
		ErrFn:   errFn,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	hsGetFeeds := append(hs["GetFeeds"], wrapper.GetFeeds)
	router.Get(options.BaseURL+"/", hsGetFeeds[0], hsGetFeeds[1:]...)

	hsNewFeed := append(hs["NewFeed"], wrapper.NewFeed)
	router.Post(options.BaseURL+"/", hsNewFeed[0], hsNewFeed[1:]...)

	hsDeleteFeed := append(hs["DeleteFeed"], wrapper.DeleteFeed)
	router.Delete(options.BaseURL+"/:id", hsDeleteFeed[0], hsDeleteFeed[1:]...)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYbU/byhL+K6O9VypIrp1Ce1Xl0+UW2qa6fRHkqB8oqhZ7Ei/Yu+7uOCGN8t+PdtbB",
	"TmKgPUI9OlK/IPB6Z555eZ4ZsxSpKSujUZMTw6VwaY6l5F+PsUDCU+Q/ZFF8nIjh+VJU1lRoSYXnKvM/",
	"J8aWksRQ1LXKRCRoUaEYCkdW6alYrW6fmMsrTEmsoqX4t8WJGIp/JS2ApPGevEGNVqXe9+piFYnXiOxn",
	"03dqURJmX73nDoZMEu5iiETG8fzw6z8UWST019SU5Tp9zbHShFO0/rwy6s4zwhvqnLRGSVGB/Sf8YClQ",
	"16UYnotSREKKSFyJSDhx0QOwtkWPpZ6SiE7Wd3NtMvaboUutqkgZLYbiFCuLDjWBRaqtBouuLgj822Am",
	"YPFbjY5iGE1AEcylA41TSWqGEaC1xkIuqwo1SAKHdoYWnMoQpM6gNI6KBcwV5fDi5gYcSaod246/6NZi",
	"ZZwKFhemBmkRKMdgPYYTRTnaCFydpuhc/EW3RexUokTn5LQnwnGuHOBNVUilYZ5LeuJgapSegtEMTW0E",
	"Hfc2v0+Dsr6Fz0MiW4cXvXUg3/Buh3o/Splou3oZklSF2w3P+9lz+2DXhZT+wEehCEu+cJ9T5mXbStJa",
	"udiJODjvidQz+wPOvZFT/Lbbc38vPbohBIfN7b6S3Ybx1yv285cuot4yP1S0Tsp7ZODCP3OY1lbR4sxf",
	"CbYvUVq0RzXl7V+v1+L47vPYJ5jfFsPmtKVCTlSJlTes9MQEOdEkU64uloxZlPjfusiVK2MWWi3Z1HtZ",
	"Xsq6gLfKSV9MLhcbdMMkaS+wvnc7+0jD2/H4E5yenI3h6NMIMpPW5brDQV6amoBpBmdoZypl7hYqRe24",
	"hRoAR5VMc4SDeLDjfT6fx5KPY2OnSXPXJf8fvTr5cHby9CAexDmVRZB6W7qPk8ZVx4iby+kUbaxMwu8k",
	"4ra/xRgJrzdBikjM0LoQ4yAexANv3VSoZaXEUBzyo0hUknKuW+J/TJH6xJsle9JIwOUCpmqGGippZYmE",
	"NgaWWV9zY9X3kLgcZYYWKmtmKsOMlXomC5VFrMemLrL1MKjQOqNlob5jxm5cq8drqZYw9ROCzcyNfkIb",
	"t4Jc+xZn56NMDG/VkYNskDrmzbZyI/j+83PIO48A2TeUsFdKpfcjkLAn3fV+BFewd2Uu9yNwsOdyM99n",
	"BfRWvtVoF207ckN3tYFsjU3ny58RHs/4TbyjY4/Ujy6P9i4AzI3W3YOLV19WzGTikLreXARlXZCqCoWZ",
	"74TDAc9sX6VKOgfPdqvL98BKPeUUHz57+p9BDMc4kXVBQxiE2vXFEPxvxLE9kb22WXSV8YTyLxwMBmvd",
	"QM3NLKuqUCn3RXLlfHDLjsH7NbSdr6xKmyl6g9QE1ywNk7qANZjY0+35o4JpBX0Xy3tZhBJD7dBu7FO+",
	"NlMkIL+hhN0oglJeI7i62YGa14Hzz3RjpjYxPP9FMYxbgOttT3HrWQTlQBuf55xT3oqQh6zQMdQXvyzd",
	"n7Eo4FqbeVgfI9AelO9Kq2UBk9qygsg0bEl8n/t9C5/fXBLeGTeRbdNzB8AfGm8qTAmzgEB0pzGLXHcO",
	"n1+soqWniqvLUtpFp3n33H74+nB0x1LrZ2IgdPiOciBvlWdTcZuFodE9dPQ/ky0erSIb60hP8yCUSqtS",
	"FltL6lrX4x09Xu1ox7PHR9vbPyOdebPYVQ7ua07xumeePyKe+/t5NIF3n8egdOA9jDY1/De7HmDXBrVe",
	"NTTROOei8u1kqbJVYFiB1PMBGf6L0pXjZhlqtW50vMu5cK2h3b17Ttgb2CIZCDButwe/Bm4tD3fvLg8t",
	"E7sz+eDROqf9Z9MdIrCVPGcm1AQb5tnBI86ze8H4moAsLMpssYHgN63/kbRuCCrXnOa7drYmW/vJN0wS",
	"/uCKB8OXg5eHiaxUMhv4L+Y/AwAA//9YAfMDRRUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
